damage.pistol_light=5.5 #double | default: 5.5
damage.pistol_heavy=11 #double | default: 11
damage.pistol_service=7 #double | default: 7
damage.revolver_compact=7 #double | default: 7
damage.revolver_magnum=12 #double | default: 12
damage.revolver_coltarmy=12 #double | default: 12
damage.smg_machinepistol=5 #double | default: 5
damage.smg_rapid=5 #double | default: 5
damage.smg_heavy=6.7 #double | default: 6.7
damage.shotgun_doublebarrel=6 #double | default: 6
damage.shotgun_combat=6 #double | default: 6
damage.shotgun_riot=4 #double | default: 4
damage.assaultrifle_light=7 #double | default: 7
damage.assaultrifle_heavy=11 #double | default: 11
damage.assaultrifle_rus=8 #double | default: 8
damage.sniper_classic=22 #double | default: 22
damage.sniper_arctic=26 #double | default: 26
damage.sniper_cowboy=16 #double | default: 16
damage.sniper_marksman=12.5 #double | default: 12.5
damage.sniper_dragunov=16 #double | default: 16
damage.lmg_m60=8 #double | default: 8
damage.lmg_minigun=6 #double | default: 6
damage.amr_classic=50 #double | default: 50

