#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Fri Mar 20 23:12:04 YAKT 2026
alwaysLogTamperWarnings=true
