#KubeJS Common Properties
#Tue Mar 17 01:06:13 GMT+09:00 2026
allowAsyncStreams=true
announceReload=true
creativeModeTabIcon=minecraft\:purple_dye
hideServerScriptErrors=false
ignoreCustomUniqueRecipeIds=false
matchJsonRecipes=true
packmode=
saveDevPropertiesInConfig=false
serverOnly=false
startupErrorGUI=true
startupErrorReportUrl=
